### ISSUE TITLE
Generated VCF files are empty

### ISSUE THREAD

**Issue by ffranr** [iqbal-lab-org/py-cortex-api#1]
This raises an error when inspecting the empty VCF file. Exception generated here: https://github.com/iqbal-lab-org/py-cortex-api/blob/d2d32dab1bc262edaebefc5427266a91bb0ec8c4/cortex/calls.py#L79

The generated VCF files are completely empty. I'm not certain if this is due to the data that I used for testing. This is the data that I used: [data.zip](https://github.com/iqbal-lab-org/py-cortex-api/files/2120191/data.zip)

Test script:
```python
import cortex
cortex.calls("./infer.fasta", "./reads", "./out", "sample_name")
```

Exception traceback:
```
  File "/home/rffrancon/Documents/py-cortex-api/cortex/calls.py", line 182, in run
    _cleanup_calls_files(sample_name, calls_paths)
  File "/home/rffrancon/Documents/py-cortex-api/cortex/calls.py", line 124, in _cleanup_calls_files
    _replace_sample_name_in_vcf(filename, tmp_vcf, sample_name)
  File "/home/rffrancon/Documents/py-cortex-api/cortex/calls.py", line 79, in _replace_sample_name_in_vcf
    raise Exception('No #CHROM line found in VCF file', infile)
Exception: ('No #CHROM line found in VCF file', '/home/rffrancon/tmp/out/cortex.out/vcfs/cortex_wk_flow_I_RefCC_FINALcombined_BC_calls_at_all_k.raw.vcf')
```

**Comment by iqbal-lab** [comment]
What are the reads. Where are they from, and what is the reference?

**Comment by iqbal-lab** [comment]
There will be an empty vcf if there are no variants, but it should not be malformed

**Comment by iqbal-lab** [comment]
Hm - had a look at the data. Those don't look like real reads:

`@0
GGACCCAGCAGTGATGCTAATCTCAGCGCTCCGCTGACCCCTCAGCAAAGGGCTTGGCTCAATCTCGTCCAGCCATTGACCATCGTCGAGGGGTTTGCTCTGTTATCCGTGCCGAGCAGCTTTGTCCAAAACGAAATCGAGCGCCATCTG
+
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

@1
GGACCCAGCAGTGATGCTAATCTCAGCGCTCCGCTGACCCCTCAGCAAAGGGCTTGGCTCAATCTCGTCCAGCCATTGACCATCGTCGAGGGGTTTGCTCTGTTATCCGTGCCGAGCAGCTTTGTCCAAAACGAAATCGAGCGCCATCTC
+
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH`

and there are only 2000. So that's really <1x depth of the genome, and there will be no calls. Is this meant to be a small test? If so you can drop genome size to 200bp or something, but have decent depth.

I think there is however a bug in Cortex if it produces an empty VCF without a CHROM line.
